apiVersion: v1
kind: Service
metadata:
  name: citricloud-backend
  namespace: citricloud
spec:
  selector:
    app: citricloud-backend
  ports:
    - name: http
      port: 4000
      targetPort: 4000
  type: ClusterIP
