apiVersion: v1
kind: Service
metadata:
  name: citricloud-frontend
  namespace: citricloud
spec:
  selector:
    app: citricloud-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
