apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: citricloud
  namespace: citricloud
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - citricloud.com
      secretName: citricloud-tls
  rules:
    - host: citricloud.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: citricloud-backend
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: citricloud-frontend
                port:
                  number: 80
