apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: citricloud
  namespace: citricloud
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - citricloud.com
      secretName: citricloud-tls
  rules:
    - host: citricloud.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: citricloud-backend
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: citricloud-frontend
                port:
                  number: 80
